# Generated by Django 2.2.5 on 2020-01-31 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0006_auto_20200131_0014'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TalkSchedule',
            new_name='SpeakerSchedule',
        ),
        migrations.AlterModelOptions(
            name='speakerschedule',
            options={'managed': True, 'verbose_name_plural': 'speaker Schedule'},
        ),
    ]
