# Generated by Django 2.2.5 on 2020-01-30 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='user',
            new_name='created_by',
        ),
    ]
