# Generated by Django 2.2.5 on 2020-02-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200130_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={},
        ),
    ]
