# Generated by Django 2.2.5 on 2020-02-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200208_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='website',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text='Link to Event Website'),
        ),
    ]
