# Generated by Django 2.2.5 on 2020-01-30 23:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('image', models.ImageField(default='sponsor.png', upload_to='sponsor/')),
                ('name', models.CharField(help_text='What is the name of the Organization', max_length=50, null=True)),
                ('twitter', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
