# Generated by Django 2.2.5 on 2020-01-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200130_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='team.png', upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin',
            field=models.CharField(help_text='Please enter only the user name eg. in/mawy7 ', max_length=100),
        ),
    ]
