# Generated by Django 2.2.5 on 2020-01-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200130_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='linkedin',
            field=models.CharField(default=' ', help_text='Please enter only the user name eg. in/mawy7 ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='', help_text='What is the name of team member', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.CharField(default=' ', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True),
        ),
    ]
