# Generated by Django 2.2.5 on 2020-02-08 15:30

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20200131_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='team_member_image',
            new_name='display_image',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='team_member_linkedin',
            new_name='member_linkedin',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='team_member_name',
            new_name='member_name',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='team_member_twitter',
            new_name='member_twitter',
        ),
        migrations.AddField(
            model_name='about',
            name='dispaly_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='about',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='member_name'),
        ),
    ]
