# Generated by Django 2.2.5 on 2020-02-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='speaker_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
