# Generated by Django 2.2.5 on 2020-02-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='team.png', upload_to='static/photos/'),
        ),
    ]
