# Generated by Django 2.2.5 on 2020-02-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_slide_speaker_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='video_youtube_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_description',
        ),
    ]
