# Generated by Django 2.2.5 on 2020-02-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20200209_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='speaker_name',
            new_name='slide_src',
        ),
    ]
