# Generated by Django 2.2.5 on 2020-02-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20200210_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='document',
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_url',
            field=models.CharField(blank=True, default='', help_text='Link to Slide', max_length=200),
        ),
    ]
