# Generated by Django 2.2.5 on 2020-02-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20200212_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='team.png', upload_to='photos/'),
        ),
    ]
